name: calculadora_imc
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.8

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  build_runner: ^2.11.0
  mockito: ^5.6.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
